### PR TITLE
fix(api): fetch up-to-date channels from neynar API

### LINKED ISSUE #55: farcaster: keep the channel registry up to date automatically
Currently we copy paste from https://raw.githubusercontent.com/neynarxyz/farcaster-channels/main/warpcast.json
every so often, we need a better solution

### LINKED ISSUE #126: editor: migrate channel search data source to warpcast channel list
Warpcast now hosts an official channel list on their API https://api.warpcast.com/v2/all-channels

### PR DESCRIPTION
**Pull request by stephancill**
## Change Summary

Update `api/farcaster/channels` route to fetch channels list from Neynar API in the, which mirrors new Warpcast API and includes up-to-date permissionless channels.

Fixes #55 
Fixes #126 

## Merge Checklist

- [x] PR has a changeset
- [x] PR includes documentation if necessary
- [x] PR updates the [rich-embed examples](https://github.com/mod-protocol/mod/blob/main/examples/nextjs-shadcn/src/app/embeds.tsx) if necessary
- [x] includes a parallel PR for [Mod-starter](https://github.com/mod-protocol/mod-starter) and the gateway if necessary

### CODE REVIEW

File: examples/api/src/app/api/farcaster/channels/route.ts [hunk 1]
```diff
@@ -1,25 +1,41 @@
...
 
+  const channelsRes = await fetch(
+    "https://api.neynar.com/v2/farcaster/channel/list",
+    {
+      headers: {
+        api_key: process.env.NEYNAR_API_SECRET,
+      },
+    }
+  );
+  const result = await channelsRes.json();
```
Comment (davidfurlong) [inline examples/api/src/app/api/farcaster/channels/route.ts:15]: should check this request succeeds before doing this and error if it does

File: examples/api/src/app/api/farcaster/channels/route.ts [hunk 2]
```diff
@@ -1,25 +1,41 @@
...
-  ...channels.sort((a, b) => (a.name < b.name ? -1 : 1)),
-];
+import { NextRequest, NextResponse } from "next/server";
 
 export async function GET(request: NextRequest) {
   const { searchParams } = new URL(request.url);
   const q = searchParams.get("q");
 
+  const channelsRes = await fetch(
+    "https://api.neynar.com/v2/farcaster/channel/list",
```
Comment (davidfurlong) [inline examples/api/src/app/api/farcaster/channels/route.ts:8]: how do you feel about this re opencast? I know you wanted an external api-less solution for opencast

**Review by davidfurlong — CHANGES_REQUESTED** [review]

File: examples/api/src/app/api/farcaster/channels/route.ts (hunk 2 above)
Comment (stephancill) [reply examples/api/src/app/api/farcaster/channels/route.ts:8]: since channels are basically warpcast-only at this stage there is no other option for the time being so this is the recommended method (see this thread with dan and rish https://warpcast.com/dwr.eth/0xaa065936)
